dict_final = {
    'Songs Of Experience': {
        'Nome Álbum Split:': ['songs', 'of', 'experience'],
        'Músicas:': ['Love Is All We Have Left', 'Lights of Home', "You're the Best Thing About Me", 'Get Out Of Your Own Way', 'American Soul', 'Summer of Love', 'Red Flag Day', 'The Showman (Little More Better)', 'The Little Things That Give You Away', 'Landlady', 'The Blackout', 'Love Is Bigger Than Anything in Its Way', '13 (There Is a Light)', 'Ordinary Love (Extraordinary Mix) (Deluxe Bonus)', 'Book of Your Heart (Deluxe Bonus)', "Lights of Home (St Peter's String Version) (Deluxe Bonus)", "You're the Best Thing About Me (U2 vs. Kygo) (Deluxe Bonus)"],
        'Nome Músicas Split:': ['love', 'is', 'all', 'we', 'have', 'left', 'lights', 'of', 'home', 'youre', 'the', 'best', 'thing', 'about', 'me', 'get', 'out', 'of', 'your', 'own', 'way', 'american', 'soul', 'summer', 'of', 'love', 'red', 'flag', 'day', 'the', 'showman', 'little', 'more', 'better', 'the', 'little', 'things', 'that', 'give', 'you', 'away', 'landlady', 'the', 'blackout', 'love', 'is', 'bigger', 'than', 'anything', 'in', 'its', 'way', '13', 'there', 'is', 'a', 'light', 'ordinary', 'love', 'extraordinary', 'mix', 'deluxe', 'bonus', 'book', 'of', 'your', 'heart', 'deluxe', 'bonus', 'lights', 'of', 'home', 'st', 'peters', 'string', 'version', 'deluxe', 'bonus', 'youre', 'the', 'best', 'thing', 'about', 'me', 'u2', 'vs', 'kygo', 'deluxe', 'bonus'],
        'Quantidade de Musicas': 17,
        'Links Musicas': ['https://www.vagalume.com.br/u2/love-is-all-we-have-left.html', 'https://www.vagalume.com.br/u2/lights-of-home.html', 'https://www.vagalume.com.br/u2/youre-the-best-thing-about-me.html', 'https://www.vagalume.com.br/u2/get-out-of-your-own-way.html', 'https://www.vagalume.com.br/u2/american-soul.html', 'https://www.vagalume.com.br/u2/summer-of-love.html', 'https://www.vagalume.com.br/u2/red-flag-day.html', 'https://www.vagalume.com.br/u2/the-showman-little-more-better.html', 'https://www.vagalume.com.br/u2/the-little-things-that-give-you-away.html', 'https://www.vagalume.com.br/u2/landlady.html', 'https://www.vagalume.com.br/u2/the-blackout.html', 'https://www.vagalume.com.br/u2/love-is-bigger-than-anything-in-its-way.html', 'https://www.vagalume.com.br/u2/13-there-is-a-light.html', 'https://www.vagalume.com.br/u2/ordinary-love.html', 'https://www.vagalume.com.br/u2/book-of-your-heart.html', 'https://www.vagalume.com.br/u2/lights-of-home.html', 'https://www.vagalume.com.br/u2/youre-the-best-thing-about-me.html']
    },
    'Songs of Innocence': {
        'Nome Álbum Split:': ['songs', 'of', 'innocence'],
        'Músicas:': ['The Miracle (Of Joey Ramone)', 'Every Breaking Wave', 'California (There Is no End To Love)', 'Song For Someone', 'Iris (Hold Me Close)', 'Volcano', 'Raised By Wolves', 'Cedarwood Road', 'Sleep Like a Baby Tonight', 'This Is Where You Can Reach Me Now', 'The Troubles'],
        'Nome Músicas Split:': ['the', 'miracle', 'of', 'joey', 'ramone', 'every', 'breaking', 'wave', 'california', 'there', 'is', 'no', 'end', 'to', 'love', 'song', 'for', 'someone', 'iris', 'hold', 'me', 'close', 'volcano', 'raised', 'by', 'wolves', 'cedarwood', 'road', 'sleep', 'like', 'a', 'baby', 'tonight', 'this', 'is', 'where', 'you', 'can', 'reach', 'me', 'now', 'the', 'troubles'],
        'Quantidade de Musicas': 11,
        'Links Musicas': ['https://www.vagalume.com.br/u2/the-miracle-of-joey-ramone.html', 'https://www.vagalume.com.br/u2/every-breaking-wave.html', 'https://www.vagalume.com.br/u2/california-there-is-no-end-to-love.html', 'https://www.vagalume.com.br/u2/song-for-someone.html', 'https://www.vagalume.com.br/u2/iris-hold-me-close.html', 'https://www.vagalume.com.br/u2/volcano.html', 'https://www.vagalume.com.br/u2/raised-by-wolves.html', 'https://www.vagalume.com.br/u2/cedarwood-road.html', 'https://www.vagalume.com.br/u2/sleep-like-a-baby-tonight.html', 'https://www.vagalume.com.br/u2/this-is-where-you-can-reach-me-now.html', 'https://www.vagalume.com.br/u2/the-troubles.html']
    },
    'No Line On The Horizon': {
        'Nome Álbum Split:': ['no', 'line', 'on'],
        'Músicas:': ['No Line On The Horizon', 'Magnificent', 'Moment Of Surrender', 'Unknown Caller', "I'll go crazy if I don't go crazy tonight", 'Get On Your Boots', 'Stand Up Comedy', 'Fez / Being Born', 'White As Snow', 'Breathe', 'Cedars Of Lebanon'],
        'Nome Músicas Split:': ['no', 'line', 'on', 'the', 'horizon', 'magnificent', 'moment', 'of', 'surrender', 'unknown', 'caller', 'ill', 'go', 'crazy', 'if', 'i', 'dont', 'go', 'crazy', 'tonight', 'get', 'on', 'your', 'boots', 'stand', 'up', 'comedy', 'fez', '', 'being', 'born', 'white', 'as', 'snow', 'breathe', 'cedars', 'of', 'lebanon'],
        'Quantidade de Musicas': 11,
        'Links Musicas': ['https://www.vagalume.com.br/u2/no-line-on-the-horizon.html', 'https://www.vagalume.com.br/u2/magnificent.html', 'https://www.vagalume.com.br/u2/moment-of-surrender.html', 'https://www.vagalume.com.br/u2/unknown-caller.html', 'https://www.vagalume.com.br/u2/ill-go-crazy-if-i-dont-go-crazy-tonight.html', 'https://www.vagalume.com.br/u2/get-on-your-boots.html', 'https://www.vagalume.com.br/u2/stand-up-comedy.html', 'https://www.vagalume.com.br/u2/fez-being-born.html', 'https://www.vagalume.com.br/u2/white-as-snow.html', 'https://www.vagalume.com.br/u2/breathe.html', 'https://www.vagalume.com.br/u2/cedars-of-lebanon.html']
    },
    'U218 Singles': {
        'Nome Álbum Split:': ['the', 'horizon', 'u218'],
        'Músicas:': ['Beautiful Day', "I Still Haven't Found What I'm Looking For", 'Pride (In the Name of Love)', 'With Or Without You', 'Vertigo', "New Year's Day", 'Mysterious Ways', 'Stuck In A Moment', 'Where The Streets Have No Name', 'Sweetest Thing', 'Sunday, Bloody Sunday', 'One', 'Desire', 'Walk On', 'Elevation', "Sometimes You Can't Make It On Your Own", 'The Saints Are Coming', 'Window In The Skies'],
        'Nome Músicas Split:': ['beautiful', 'day', 'i', 'still', 'havent', 'found', 'what', 'im', 'looking', 'for', 'pride', 'in', 'the', 'name', 'of', 'love', 'with', 'or', 'without', 'you', 'vertigo', 'new', 'years', 'day', 'mysterious', 'ways', 'stuck', 'in', 'a', 'moment', 'where', 'the', 'streets', 'have', 'no', 'name', 'sweetest', 'thing', 'sunday,', 'bloody', 'sunday', 'one', 'desire', 'walk', 'on', 'elevation', 'sometimes', 'you', 'cant', 'make', 'it', 'on', 'your', 'own', 'the', 'saints', 'are', 'coming', 'window', 'in', 'the', 'skies'],
        'Quantidade de Musicas': 18,
        'Links Musicas': ['https://www.vagalume.com.br/u2/beautiful-day.html', 'https://www.vagalume.com.br/u2/i-still-havent-found-what-im-looking-for.html', 'https://www.vagalume.com.br/u2/pride-in-the-name-of-love.html', 'https://www.vagalume.com.br/u2/with-or-without-you.html', 'https://www.vagalume.com.br/u2/vertigo.html', 'https://www.vagalume.com.br/u2/new-years-day.html', 'https://www.vagalume.com.br/u2/mysterious-ways.html', 'https://www.vagalume.com.br/u2/stuck-in-a-moment-you-cant-get-out-of.html', 'https://www.vagalume.com.br/u2/where-the-streets-have-no-name.html', 'https://www.vagalume.com.br/u2/sweetest-thing.html', 'https://www.vagalume.com.br/u2/sunday-bloody-sunday.html', 'https://www.vagalume.com.br/u2/one.html', 'https://www.vagalume.com.br/u2/desire.html', 'https://www.vagalume.com.br/u2/walk-on.html', 'https://www.vagalume.com.br/u2/elevation.html', 'https://www.vagalume.com.br/u2/sometimes-you-cant-make-it-on-your-own.html', 'https://www.vagalume.com.br/u2/the-saints-are-coming.html', 'https://www.vagalume.com.br/u2/window-in-the-skies.html']
    },
    'How to Dismantle an Atomic Bomb': {
        'Nome Álbum Split:': ['singles', 'how', 'to'],
        'Músicas:': ['Vertigo', 'Miracle Drug', "Sometimes You Can't Make It On You Own", 'Love And Peace', 'City Of Blinding Lights', 'All Because Of You', 'A Man And A Woman', 'Crumbs From Your Table', 'One Step Closer', 'Original Of The Species', 'Yahweh'],
        'Nome Músicas Split:': ['vertigo', 'miracle', 'drug', 'sometimes', 'you', 'cant', 'make', 'it', 'on', 'you', 'own', 'love', 'and', 'peace', 'city', 'of', 'blinding', 'lights', 'all', 'because', 'of', 'you', 'a', 'man', 'and', 'a', 'woman', 'crumbs', 'from', 'your', 'table', 'one', 'step', 'closer', 'original', 'of', 'the', 'species', 'yahweh'],
        'Quantidade de Musicas': 11,
        'Links Musicas': ['https://www.vagalume.com.br/u2/vertigo.html', 'https://www.vagalume.com.br/u2/miracle-drug.html', 'https://www.vagalume.com.br/u2/sometimes-you-cant-make-it-on-your-own.html', 'https://www.vagalume.com.br/u2/love-and-peace-or-else.html', 'https://www.vagalume.com.br/u2/city-of-blinding-lights.html', 'https://www.vagalume.com.br/u2/all-because-of-you.html', 'https://www.vagalume.com.br/u2/a-man-and-a-woman.html', 'https://www.vagalume.com.br/u2/crumbs-from-your-table.html', 'https://www.vagalume.com.br/u2/one-step-closer.html', 'https://www.vagalume.com.br/u2/original-of-the-specie.html', 'https://www.vagalume.com.br/u2/yahweh.html']
    },
    'The Best 1990-2000': {
        'Nome Álbum Split:': ['dismantle', 'an', 'atomic'],
        'Músicas:': ['Even Better Than The Real Thing', 'Misteroius Ways', 'Beautiful Day', 'Electrical Storm', 'One', 'Miss Sarajevo', 'Stay (Faraway , So Close !)', "Stuck In A Moment You Can't Get Out Of", 'Gone', 'Until The End Of The World', 'The Hands That Built America (Nova)', 'DiscothÃ¨que', 'Hold Me , Thrill Me , Kiss Me , Kill Me', 'Staring At The Sun', 'Numb', 'The First Time'],
        'Nome Músicas Split:': ['even', 'better', 'than', 'the', 'real', 'thing', 'misteroius', 'ways', 'beautiful', 'day', 'electrical', 'storm', 'one', 'miss', 'sarajevo', 'stay', 'faraway', ',', 'so', 'close', '!', 'stuck', 'in', 'a', 'moment', 'you', 'cant', 'get', 'out', 'of', 'gone', 'until', 'the', 'end', 'of', 'the', 'world', 'the', 'hands', 'that', 'built', 'america', 'nova', 'discothã¨que', 'hold', 'me', ',', 'thrill', 'me', ',', 'kiss', 'me', ',', 'kill', 'me', 'staring', 'at', 'the', 'sun', 'numb', 'the', 'first', 'time'],
        'Quantidade de Musicas': 16,
        'Links Musicas': ['https://www.vagalume.com.br/u2/even-better-than-the-real-thing.html', 'https://www.vagalume.com.br/u2/mysterious-ways.html', 'https://www.vagalume.com.br/u2/beautiful-day.html', 'https://www.vagalume.com.br/u2/electrical-storm.html', 'https://www.vagalume.com.br/u2/one.html', 'https://www.vagalume.com.br/u2/miss-sarajevo.html', 'https://www.vagalume.com.br/u2/stay-faraway-so-close.html', 'https://www.vagalume.com.br/u2/stuck-in-a-moment-you-cant-get-out-of.html', 'https://www.vagalume.com.br/u2/gone.html', 'https://www.vagalume.com.br/u2/until-the-end-of-the-world.html', 'https://www.vagalume.com.br/u2/the-hands-that-built-america.html', 'https://www.vagalume.com.br/u2/discotheque.html', 'https://www.vagalume.com.br/u2/hold-me-thrill-me-kiss-me-kill-me.html', 'https://www.vagalume.com.br/u2/staring-at-the-sun.html', 'https://www.vagalume.com.br/u2/numb.html', 'https://www.vagalume.com.br/u2/the-first-time.html']
    },
    "All That You Can't Leave Behind": {
        'Nome Álbum Split:': ['bomb', 'the', 'best'],
        'Músicas:': ['Beautiful Day', "Stuck in a Moment You Can't Get Out Of", 'Elevation', 'Walk On', 'Kite', 'In a Little While', 'Wild Honey', 'Peace on Earth', 'When I Look At The World', 'New York', 'Grace'],
        'Nome Músicas Split:': ['beautiful', 'day', 'stuck', 'in', 'a', 'moment', 'you', 'cant', 'get', 'out', 'of', 'elevation', 'walk', 'on', 'kite', 'in', 'a', 'little', 'while', 'wild', 'honey', 'peace', 'on', 'earth', 'when', 'i', 'look', 'at', 'the', 'world', 'new', 'york', 'grace'],
        'Quantidade de Musicas': 11,
        'Links Musicas': ['https://www.vagalume.com.br/u2/beautiful-day.html', 'https://www.vagalume.com.br/u2/stuck-in-a-moment-you-cant-get-out-of.html', 'https://www.vagalume.com.br/u2/elevation.html', 'https://www.vagalume.com.br/u2/walk-on.html', 'https://www.vagalume.com.br/u2/kite.html', 'https://www.vagalume.com.br/u2/in-a-little-while.html', 'https://www.vagalume.com.br/u2/wild-honey.html', 'https://www.vagalume.com.br/u2/peace-on-earth.html', 'https://www.vagalume.com.br/u2/when-i-look-at-the-world.html', 'https://www.vagalume.com.br/u2/new-york.html', 'https://www.vagalume.com.br/u2/grace.html']
    },
    'The Best of 1980-1990': {
        'Nome Álbum Split:': ['1990-2000', 'all', 'that'],
        'Músicas:': ['Pride (In The Name of Love)', 'New Year s Day', 'With Or Without You', 'I Still Haven t Found What I m Looking For', 'Sunday Bloody Sunday', 'Bad', 'Where The Streets Have No Name', 'I Will Follow', 'The Unforgettable Fire', 'Sweetest Thing (New Recording)', 'Desire', 'When Love Comes to Town', 'Angel of Harlem', 'All I Want Is You'],
        'Nome Músicas Split:': ['pride', 'in', 'the', 'name', 'of', 'love', 'new', 'year', 's', 'day', 'with', 'or', 'without', 'you', 'i', 'still', 'haven', 't', 'found', 'what', 'i', 'm', 'looking', 'for', 'sunday', 'bloody', 'sunday', 'bad', 'where', 'the', 'streets', 'have', 'no', 'name', 'i', 'will', 'follow', 'the', 'unforgettable', 'fire', 'sweetest', 'thing', 'new', 'recording', 'desire', 'when', 'love', 'comes', 'to', 'town', 'angel', 'of', 'harlem', 'all', 'i', 'want', 'is', 'you'],
        'Quantidade de Musicas': 14,
        'Links Musicas': ['https://www.vagalume.com.br/u2/pride-in-the-name-of-love.html', 'https://www.vagalume.com.br/u2/new-years-day.html', 'https://www.vagalume.com.br/u2/with-or-without-you.html', 'https://www.vagalume.com.br/u2/i-still-havent-found-what-im-looking-for.html', 'https://www.vagalume.com.br/u2/sunday-bloody-sunday.html', 'https://www.vagalume.com.br/u2/bad.html', 'https://www.vagalume.com.br/u2/where-the-streets-have-no-name.html', 'https://www.vagalume.com.br/u2/i-will-follow.html', 'https://www.vagalume.com.br/u2/the-unforgettable-fire.html', 'https://www.vagalume.com.br/u2/sweetest-thing.html', 'https://www.vagalume.com.br/u2/desire.html', 'https://www.vagalume.com.br/u2/when-love-comes-to-town.html', 'https://www.vagalume.com.br/u2/angel-of-harlem.html', 'https://www.vagalume.com.br/u2/all-i-want-is-you.html']
    },
    'Pop': {
        'Nome Álbum Split:': ['you', 'cant', 'leave'],
        'Músicas:': ['Discotheque', 'Do You Feel Loved', 'Mofo', 'If God Will Send His Angels', 'Staring At The Sun', 'Last Night On Earth', 'Gone', 'Miami', 'The Playboy Mansion', 'If You Wear That Velvet Dress', 'Please', 'Wake Up Dead Man'],
        'Nome Músicas Split:': ['discotheque', 'do', 'you', 'feel', 'loved', 'mofo', 'if', 'god', 'will', 'send', 'his', 'angels', 'staring', 'at', 'the', 'sun', 'last', 'night', 'on', 'earth', 'gone', 'miami', 'the', 'playboy', 'mansion', 'if', 'you', 'wear', 'that', 'velvet', 'dress', 'please', 'wake', 'up', 'dead', 'man'],
        'Quantidade de Musicas': 12,
        'Links Musicas': ['https://www.vagalume.com.br/u2/discotheque.html', 'https://www.vagalume.com.br/u2/do-you-feel-loved.html', 'https://www.vagalume.com.br/u2/mofo.html', 'https://www.vagalume.com.br/u2/if-god-will-send-his-angels.html', 'https://www.vagalume.com.br/u2/staring-at-the-sun.html', 'https://www.vagalume.com.br/u2/last-night-on-earth.html', 'https://www.vagalume.com.br/u2/gone.html', 'https://www.vagalume.com.br/u2/miami.html', 'https://www.vagalume.com.br/u2/the-playboy-mansion.html', 'https://www.vagalume.com.br/u2/if-you-wear-that-velvet-dress.html', 'https://www.vagalume.com.br/u2/please.html', 'https://www.vagalume.com.br/u2/wake-up-dead-man.html']
    },
    'Zooropa': {
        'Nome Álbum Split:': ['behind', 'the', 'best'],
        'Músicas:': ['Zooropa', 'Babyface', 'Numb', 'Lemon', 'Stay (Faraway, So Close!)', "Daddy's Gonna Pay For", 'Some Days Are Better Than Others', 'The First Time', 'Dirty Day', 'The Wanderer'],
        'Nome Músicas Split:': ['zooropa', 'babyface', 'numb', 'lemon', 'stay', 'faraway,', 'so', 'close!', 'daddys', 'gonna', 'pay', 'for', 'some', 'days', 'are', 'better', 'than', 'others', 'the', 'first', 'time', 'dirty', 'day', 'the', 'wanderer'],
        'Quantidade de Musicas': 10,
        'Links Musicas': ['https://www.vagalume.com.br/u2/zooropa.html', 'https://www.vagalume.com.br/u2/babyface.html', 'https://www.vagalume.com.br/u2/numb.html', 'https://www.vagalume.com.br/u2/lemon.html', 'https://www.vagalume.com.br/u2/stay-faraway-so-close.html', 'https://www.vagalume.com.br/u2/daddys-gonna-pay-for-your-crashed-car.html', 'https://www.vagalume.com.br/u2/some-days-are-better-than-others.html', 'https://www.vagalume.com.br/u2/the-first-time.html', 'https://www.vagalume.com.br/u2/dirty-day.html', 'https://www.vagalume.com.br/u2/the-wanderer.html']
    },
    'Achtung Baby': {
        'Nome Álbum Split:': ['of', '1980-1990', 'pop'],
        'Músicas:': ['Zoo Station', 'Even Better Than The Real Thing', 'One', 'Until The End Of The World', "Who's Gonna Ride Your Wild Horses", 'So Cruel', 'The Fly', 'Mysterious Ways', "Tryin' To Thow Your Arms Around The World", 'Ultra Violet ( Light My Way )', 'Acrobat', 'Love Is Blindness'],
        'Nome Músicas Split:': ['zoo', 'station', 'even', 'better', 'than', 'the', 'real', 'thing', 'one', 'until', 'the', 'end', 'of', 'the', 'world', 'whos', 'gonna', 'ride', 'your', 'wild', 'horses', 'so', 'cruel', 'the', 'fly', 'mysterious', 'ways', 'tryin', 'to', 'thow', 'your', 'arms', 'around', 'the', 'world', 'ultra', 'violet', '', 'light', 'my', 'way', '', 'acrobat', 'love', 'is', 'blindness'],
        'Quantidade de Musicas': 12,
        'Links Musicas': ['https://www.vagalume.com.br/u2/zoo-station.html', 'https://www.vagalume.com.br/u2/even-better-than-the-real-thing.html', 'https://www.vagalume.com.br/u2/one.html', 'https://www.vagalume.com.br/u2/until-the-end-of-the-world.html', 'https://www.vagalume.com.br/u2/whos-gonna-ride-your-wild-horses.html', 'https://www.vagalume.com.br/u2/so-cruel.html', 'https://www.vagalume.com.br/u2/the-fly.html', 'https://www.vagalume.com.br/u2/mysterious-ways.html', 'https://www.vagalume.com.br/u2/tryin-to-throw-your-arms-around-the-world.html', 'https://www.vagalume.com.br/u2/ultraviolet-light-my-way.html', 'https://www.vagalume.com.br/u2/acrobat.html', 'https://www.vagalume.com.br/u2/love-is-blindness.html']
    },
    'Rattle and Hum': {
        'Nome Álbum Split:': ['zooropa', 'achtung', 'baby'],
        'Músicas:': ['Helter Skelter', "Van Diemen's Land", 'Desire', 'Hawkmoon 269', 'All Along The Watchtower', "I Still Haven't Found What I'm Looking For", 'Freedom For My People', 'Silver And Gold', 'Pride (In The Name Of Love)', 'Angel Of Harlem', 'Love Rescue Me', 'When Love Comes To Town', 'Heartland', 'God Part II', 'The Star Spangled Banner', 'Bullet The Blue Sky', 'All I Want Is You'],
        'Nome Músicas Split:': ['helter', 'skelter', 'van', 'diemens', 'land', 'desire', 'hawkmoon', '269', 'all', 'along', 'the', 'watchtower', 'i', 'still', 'havent', 'found', 'what', 'im', 'looking', 'for', 'freedom', 'for', 'my', 'people', 'silver', 'and', 'gold', 'pride', 'in', 'the', 'name', 'of', 'love', 'angel', 'of', 'harlem', 'love', 'rescue', 'me', 'when', 'love', 'comes', 'to', 'town', 'heartland', 'god', 'part', 'ii', 'the', 'star', 'spangled', 'banner', 'bullet', 'the', 'blue', 'sky', 'all', 'i', 'want', 'is', 'you'],
        'Quantidade de Musicas': 17,
        'Links Musicas': ['https://www.vagalume.com.br/u2/helter-skelter.html', 'https://www.vagalume.com.br/u2/van-diemens-land.html', 'https://www.vagalume.com.br/u2/desire.html', 'https://www.vagalume.com.br/u2/hawkmoon-269.html', 'https://www.vagalume.com.br/u2/all-along-the-watchtower.html', 'https://www.vagalume.com.br/u2/i-still-havent-found-what-im-looking-for.html', 'https://www.vagalume.com.br/u2/freedom-for-my-people.html', 'https://www.vagalume.com.br/u2/silver-and-gold.html', 'https://www.vagalume.com.br/u2/pride-in-the-name-of-love.html', 'https://www.vagalume.com.br/u2/angel-of-harlem.html', 'https://www.vagalume.com.br/u2/love-rescue-me.html', 'https://www.vagalume.com.br/u2/when-love-comes-to-town.html', 'https://www.vagalume.com.br/u2/heartland.html', 'https://www.vagalume.com.br/u2/god-part-ii.html', 'https://www.vagalume.com.br/u2/the-star-spangled-banner.html', 'https://www.vagalume.com.br/u2/bullet-the-blue-sky.html', 'https://www.vagalume.com.br/u2/all-i-want-is-you.html']
    },
    'The Joshua Tree': {
        'Nome Álbum Split:': ['rattle', 'and', 'hum'],
        'Músicas:': ['Where The Streets Have No Name', "I Still Haven't Found What I'm Looking For", 'With Or Without You', 'Bullet The Blue Sky', 'Running To Stand Still', 'Red Hill Mining Town', "In God's Country", 'Trip Through Your Wires', 'One Tree Hill', 'Exit', 'Mothers Of The Disappeared'],
        'Nome Músicas Split:': ['where', 'the', 'streets', 'have', 'no', 'name', 'i', 'still', 'havent', 'found', 'what', 'im', 'looking', 'for', 'with', 'or', 'without', 'you', 'bullet', 'the', 'blue', 'sky', 'running', 'to', 'stand', 'still', 'red', 'hill', 'mining', 'town', 'in', 'gods', 'country', 'trip', 'through', 'your', 'wires', 'one', 'tree', 'hill', 'exit', 'mothers', 'of', 'the', 'disappeared'],
        'Quantidade de Musicas': 11,
        'Links Musicas': ['https://www.vagalume.com.br/u2/where-the-streets-have-no-name.html', 'https://www.vagalume.com.br/u2/i-still-havent-found-what-im-looking-for.html', 'https://www.vagalume.com.br/u2/with-or-without-you.html', 'https://www.vagalume.com.br/u2/bullet-the-blue-sky.html', 'https://www.vagalume.com.br/u2/running-to-stand-still.html', 'https://www.vagalume.com.br/u2/red-hill-mining-town.html', 'https://www.vagalume.com.br/u2/in-gods-country.html', 'https://www.vagalume.com.br/u2/trip-through-your-wires.html', 'https://www.vagalume.com.br/u2/one-tree-hill.html', 'https://www.vagalume.com.br/u2/exit.html', 'https://www.vagalume.com.br/u2/mothers-of-the-disappeared.html']
    },
    'Wide Awake in America': {
        'Nome Álbum Split:': ['the', 'joshua', 'tree'],
        'Músicas:': ['Bad (Live)', 'A Sort Of Homecoming (Live)', 'Three Sunrises', 'Love Comes Tumbling'],
        'Nome Músicas Split:': ['bad', 'live', 'a', 'sort', 'of', 'homecoming', 'live', 'three', 'sunrises', 'love', 'comes', 'tumbling'],
        'Quantidade de Musicas': 4,
        'Links Musicas': ['https://www.vagalume.com.br/u2/bad.html', 'https://www.vagalume.com.br/u2/a-sort-of-homecoming.html', 'https://www.vagalume.com.br/u2/three-sunrises.html', 'https://www.vagalume.com.br/u2/love-comes-tumbling.html']
    },
    'The Unforgettable Fire': {
        'Nome Álbum Split:': ['wide', 'awake', 'in'],
        'Músicas:': ['A Sort Of Homecoming', 'Pride', 'Wire', 'The Unforgettable Fire', 'Promenade', '4th Of July', 'Bad', 'Indian Summer Sky', 'Elvis Presley And America', 'MLK'],
        'Nome Músicas Split:': ['a', 'sort', 'of', 'homecoming', 'pride', 'wire', 'the', 'unforgettable', 'fire', 'promenade', '4th', 'of', 'july', 'bad', 'indian', 'summer', 'sky', 'elvis', 'presley', 'and', 'america', 'mlk'],
        'Quantidade de Musicas': 10,
        'Links Musicas': ['https://www.vagalume.com.br/u2/a-sort-of-homecoming.html', 'https://www.vagalume.com.br/u2/pride-in-the-name-of-love.html', 'https://www.vagalume.com.br/u2/wire.html', 'https://www.vagalume.com.br/u2/the-unforgettable-fire.html', 'https://www.vagalume.com.br/u2/promenade.html', 'https://www.vagalume.com.br/u2/4th-of-july.html', 'https://www.vagalume.com.br/u2/bad.html', 'https://www.vagalume.com.br/u2/indian-summer-sky.html', 'https://www.vagalume.com.br/u2/elvis-presley-and-america.html', 'https://www.vagalume.com.br/u2/mlk.html']
    },
    'Under a Blood Red Sky': {
        'Nome Álbum Split:': ['america', 'the', 'unforgettable'],
        'Músicas:': ['Gloria', "11 O'Clock Tick Tock", 'I Will Follow', 'Party Girl', 'Sunday Bloody Sunday', 'The Electric Co.', 'New Years Day', "'40'"],
        'Nome Músicas Split:': ['gloria', '11', 'oclock', 'tick', 'tock', 'i', 'will', 'follow', 'party', 'girl', 'sunday', 'bloody', 'sunday', 'the', 'electric', 'co', 'new', 'years', 'day', '40'],
        'Quantidade de Musicas': 8,
        'Links Musicas': ['https://www.vagalume.com.br/u2/gloria.html', 'https://www.vagalume.com.br/u2/11-oclock-tick-tock.html', 'https://www.vagalume.com.br/u2/i-will-follow.html', 'https://www.vagalume.com.br/u2/party-girl.html', 'https://www.vagalume.com.br/u2/sunday-bloody-sunday.html', 'https://www.vagalume.com.br/u2/the-electric-co.html', 'https://www.vagalume.com.br/u2/new-years-day.html', 'https://www.vagalume.com.br/u2/40.html']
    },
    'War': {
        'Nome Álbum Split:': ['fire', 'under', 'a'],
        'Músicas:': ['Sunday Bloody Sunday', 'Seconds', "New Year's Day", 'Like A Song...', 'Drowning Man', 'The Refugee', 'Two Hearts Beat As One', 'Red Light', 'Surrender', "'40'"],
        'Nome Músicas Split:': ['sunday', 'bloody', 'sunday', 'seconds', 'new', 'years', 'day', 'like', 'a', 'song', 'drowning', 'man', 'the', 'refugee', 'two', 'hearts', 'beat', 'as', 'one', 'red', 'light', 'surrender', '40'],
        'Quantidade de Musicas': 10,
        'Links Musicas': ['https://www.vagalume.com.br/u2/sunday-bloody-sunday.html', 'https://www.vagalume.com.br/u2/seconds.html', 'https://www.vagalume.com.br/u2/new-years-day.html', 'https://www.vagalume.com.br/u2/like-a-song.html', 'https://www.vagalume.com.br/u2/drowning-man.html', 'https://www.vagalume.com.br/u2/the-refugee.html', 'https://www.vagalume.com.br/u2/two-hearts-beat-as-one.html', 'https://www.vagalume.com.br/u2/red-light.html', 'https://www.vagalume.com.br/u2/surrender.html', 'https://www.vagalume.com.br/u2/40.html']
    },
    'October': {
        'Nome Álbum Split:': ['blood', 'red', 'sky'],
        'Músicas:': ['Gloria', 'I Fall Down', 'I Threw A Brick Through A Window', 'Rejoice', 'Fire', 'Tomorrow', 'October', 'With A Shout', 'Stranger In A Strange Land', 'Scarlet', 'Is That All?'],
        'Nome Músicas Split:': ['gloria', 'i', 'fall', 'down', 'i', 'threw', 'a', 'brick', 'through', 'a', 'window', 'rejoice', 'fire', 'tomorrow', 'october', 'with', 'a', 'shout', 'stranger', 'in', 'a', 'strange', 'land', 'scarlet', 'is', 'that', 'all?'],
        'Quantidade de Musicas': 11,
        'Links Musicas': ['https://www.vagalume.com.br/u2/gloria.html', 'https://www.vagalume.com.br/u2/i-fall-down.html', 'https://www.vagalume.com.br/u2/i-threw-a-brick-through-a-window.html', 'https://www.vagalume.com.br/u2/rejoice.html', 'https://www.vagalume.com.br/u2/fire.html', 'https://www.vagalume.com.br/u2/tomorrow.html', 'https://www.vagalume.com.br/u2/october.html', 'https://www.vagalume.com.br/u2/with-a-shout-jerusalem.html', 'https://www.vagalume.com.br/u2/stranger-in-a-strange-land.html', 'https://www.vagalume.com.br/u2/scarlet.html', 'https://www.vagalume.com.br/u2/is-that-all.html']
    },
    'Boy': {
        'Nome Álbum Split:': ['war', 'october', 'boy'],
        'Músicas:': ['I Will Follow', 'Twilight', 'An Cat Dubh', 'Into The Heart', 'Out Of Control', 'Stories For Boys', 'The Ocean', 'A Day Without Me', 'Another Time, Another Place', 'The Electric Co.', 'Shadows And Tall Trees'],
        'Nome Músicas Split:': ['i', 'will', 'follow', 'twilight', 'an', 'cat', 'dubh', 'into', 'the', 'heart', 'out', 'of', 'control', 'stories', 'for', 'boys', 'the', 'ocean', 'a', 'day', 'without', 'me', 'another', 'time,', 'another', 'place', 'the', 'electric', 'co', 'shadows', 'and', 'tall', 'trees'],
        'Quantidade de Musicas': 11,
        'Links Musicas': ['https://www.vagalume.com.br/u2/i-will-follow.html', 'https://www.vagalume.com.br/u2/twilight.html', 'https://www.vagalume.com.br/u2/an-cat-dubh.html', 'https://www.vagalume.com.br/u2/into-the-heart.html', 'https://www.vagalume.com.br/u2/out-of-control.html', 'https://www.vagalume.com.br/u2/stories-for-boys.html', 'https://www.vagalume.com.br/u2/the-ocean.html', 'https://www.vagalume.com.br/u2/a-day-without-me.html', 'https://www.vagalume.com.br/u2/another-time-another-place.html', 'https://www.vagalume.com.br/u2/the-electric-co.html', 'https://www.vagalume.com.br/u2/shadows-and-tall-trees.html']
    }
}

print(dict_final['Boy']['Links Musicas'])